cgran/urls.py
from django.urls import include, re_path
from django.contrib import admin

urlpatterns = [
    re_path(r'^', include('ootlist.urls', namespace='ootlist')), # root url
    re_path(r'^admin/', admin.site.urls),
]

ootlist/urls.py
from django.urls import re_path

from . import views

app_name = 'ootlist'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'submit', views.submit, name='submit'),
    re_path(r'refresh', views.refresh, name='refresh'),
    re_path(r'^(?P<oot_id>[0-9]+)/$', views.oot_page, name='oot_page'),
]

ootlist/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Outoftreemodule(models.Model):
    name = models.CharField(max_length=500)
    tags = models.CharField(max_length=500, null=True, blank=True)
    description = models.TextField(max_length=5000, null=True, blank=True)
    repo = models.URLField(max_length=500, null=True, blank=True)
    added_date = models.DateField(null=True, blank=True)
    status = models.CharField(max_length=30, null=True, blank=True) # green, yellow, red
    last_commit = models.DateField(null=True, blank=True)
    author = models.CharField(max_length=500, null=True, blank=True)
    dependencies = models.TextField(max_length=5000, null=True, blank=True)
    copyright_owner = models.CharField(max_length=500, null=True, blank=True)
    icon = models.ImageField(upload_to='images/', max_length=500, null=True, blank=True)
    website = models.CharField(max_length=500, null=True, blank=True)
    gr_supported_version = models.CharField(max_length=500, null=True, blank=True)
    body_text = models.TextField(max_length=50000, null=True, blank=True)

class Packageversion(models.Model):
    os_name = models.CharField(max_length=500)
    gr_version_string = models.CharField(max_length=500)

ootlist/forms.py
from django import forms

class SearchForm(forms.Form):
    search_text = forms.CharField(label='', max_length=100, required = False, widget=forms.TextInput(attrs={'placeholder': 'search for text'}))

ootlist/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.template import loader
from django_tables2 import RequestConfig
from django.shortcuts import redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

from .models import Outoftreemodule
from .models import Packageversion
from .tables import OutoftreemoduleTable
from .forms import SearchForm

@csrf_exempt
def index(request):
    package_versions = Packageversion.objects.all()
    if request.method == 'POST': # if this is a POST request we need to process the form data
        form = SearchForm(request.POST)
        if form.is_valid(): # check whether it's valid
            # search for oots with the provided string in either the name, tags, description, authors, or body_text
            objects = (Outoftreemodule.objects.filter(name__icontains=form.cleaned_data['search_text']) |
                       Outoftreemodule.objects.filter(tags__icontains=form.cleaned_data['search_text']) |
                       Outoftreemodule.objects.filter(description__icontains=form.cleaned_data['search_text']) |
                       Outoftreemodule.objects.filter(author__icontains=form.cleaned_data['search_text']) |
                       Outoftreemodule.objects.filter(body_text__icontains=form.cleaned_data['search_text']))
            table = OutoftreemoduleTable(objects, order_by=("-last_commit")) # icontains is case-insensitive
            RequestConfig(request, paginate={'per_page': 200}).configure(table)
            return render(request, 'ootlist/index.html', {'table': table, 'form': form, 'package_versions': package_versions})
    form = SearchForm()
    table = OutoftreemoduleTable(Outoftreemodule.objects.all(), order_by=("-last_commit"))
    RequestConfig(request, paginate={'per_page': 200}).configure(table)
    return render(request, 'ootlist/index.html', {'table': table, 'form': form, 'package_versions': package_versions})

# submit your own OOT link
def submit(request):
    return render(request, 'ootlist/submit.html')

# page that shows up when you click an OOT
def oot_page(request, oot_id):
    oot = Outoftreemodule.objects.get(pk=oot_id)
    return render(request, 'ootlist/oot_page.html', {'oot': oot})

def refresh(request):
    return HttpResponse("Refresh feature moved to management command called refresh, ran with a cronjob")

ootlist/templates/ootlist/footer.html
<footer>
<hr>
<div align="center">
    <h4 style="padding-top: 30px; color: #757575">
    &copy; 2021 GNU Radio project. All rights reserved.
    <br />
    CGRAN.org is licensed under CC BY 4.0
    <br />
    CGRAN logo designed by Clarissa "K" Stiles
    </h4>
</div>
</footer>

ootlist/templates/ootlist/index.html
{% load render_table from django_tables2 %}
{% load static %}


<html>
<head>
  <title>CGRAN</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'ootlist/style.css' %}" />
  <style>
    body{
    max-width: 1080px;
    margin: 0 auto !important;
    float: none !important;
    }

.table-xtra-condensed > thead > tr > th,
.table-xtra-condensed > tbody > tr > th,
.table-xtra-condensed > tfoot > tr > th,
.table-xtra-condensed > thead > tr > td,
.table-xtra-condensed > tbody > tr > td,
.table-xtra-condensed > tfoot > tr > td {
  padding: 2px;
}

.table-xtra-condensed{
  font-size: 16px;
  color: #757575;
}

</style>
</head>

<body>


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li><a href=".">CGRAN</a></li>
      <li><a target="_blank" href="http://gnuradio.org/">GNU Radio</a></li>
      <li><a target="_blank" href="http://libvolk.org/">VOLK</a></li>
      <li><a target="_blank" href="https://github.com/gnuradio/pybombs">PyBOMBS</a></li>
      <li><a href="{% url 'ootlist:submit' %}">Submit your OOT</a></li>
    </ul>
  </div>
</nav>


<div class="row">
  <div class="col-sm-4"> <!-- remember, numbers should add to 12 -->
    <img src="{% static 'ootlist/images/cgran_logo_v2.png' %}" class="img-responsive">
  </div>
  
  <div class="col-md-8" align="center"> 
    <h3 style="color: #fd6b5c">The Comprehensive GNU Radio Archive Network</h3>
    <h4 style="padding-top: 30px; color: #757575">
    The Comprehensive GNU Radio Archive Network (CGRAN) is a free open source
    repository for 3rd party GNU Radio applications (a.k.a Out Of Tree Modules)
    that are not officially supported by the GNU Radio project.<br><br>
    GNU Radio Packaging Legend:
    </h4>

    <div class="col-md-3">
    </div>
    
    <div class="col-md-6">
    <table class="table table-striped table-xtra-condensed text-center">
      <thead>
        <tr>
          <th scope="col" class="text-center">OS</th>
          <th scope="col" class="text-nowrap text-center"><b>GR Version</th>
        </tr>
      </thead>
      <tbody>
        {% for x in package_versions %}
          <tr>
            <td>{{x.os_name}}</td>
            <td>{{x.gr_version_string}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    </div>
    
    <div class="col-md-3">
    </div>
    
  </div>
  
</div> 
  

<hr>

<div class="container" align="center">  
  <div align="left">  
    <form action="." method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Search" />
    </form>
  </div>
  {% render_table table %}
</div>

</body>

{% include 'ootlist/footer.html' %}

</html>

ootlist/templates/ootlist/oot_page.html
{% load static %}


<html>
<head>
  <title>CGRAN</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'ootlist/style.css' %}" />
</head>

<body>



<nav class="navbar navbar-default">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li><a href="javascript:history.back()">CGRAN</a></li>
      <li><a target="_blank" href="http://gnuradio.org/">GNU Radio</a></li>
      <li><a target="_blank" href="http://libvolk.org/">VOLK</a></li>
      <li><a target="_blank" href="https://github.com/gnuradio/pybombs">PyBOMBS</a></li>
      <li><a href="{% url 'ootlist:submit' %}">Submit your OOT</a></li>
    </ul>
  </div>
</nav>


<a class="btn btn-link" role="button" href="javascript:history.back()">Back</a>

<div class="container">
  <h1>  {{ oot.name }} </h1>
  <div style="float:left; width: 300px;height: 300px;">
    <img src="{{ oot.icon }}" alt="img" class="img-responsive">
  </div>
  <div class="container" style="width: 500px; float: left">
  <ul class="list-group" display="inline">
    <li class="list-group-item" style="border: none">
      <b>Tags:</b>            {{ oot.tags }}</li>
    <li class="list-group-item" style="border: none">
      <b>Developer:</b>       {{ oot.author }}</li>
    <li class="list-group-item" style="border: none">
      <b>Dependencies:</b>    {{ oot.dependencies }}</li>
    <li class="list-group-item" style="border: none">
      <b>Repository:</b>      <a href="{{ oot.repo }}">{{ oot.repo }}</a></li>

    {% if oot.website != "None" %}
    <li class="list-group-item" style="border: none">
      <b>Website:</b>         <a href="{{ oot.website }}">{{ oot.website }}</a></li>
    {% endif %}

    <li class="list-group-item" style="border: none">
      <b>Copyright Owner:</b> {{ oot.copyright_owner }}</li>
    <li class="list-group-item" style="border: none">
      <b>Supported GNU Radio versions:</b> {{ oot.gr_supported_version }}</li>
    <li class="list-group-item" style="border: none">
      <b>Brief:</b>           {{ oot.description }}</li>
  </ul>
  </div>
</div>

  <h1>Module Info</h1>
    <div class="container" style="margin-left: 2em;">
      {{ oot.body_text |safe }}
    </div>

</body>

{% include 'ootlist/footer.html' %}

</html>

ootlist/templates/ootlist/submit.html
<!DOCTYPE html>

{% load static %}

<html>

<head>
  <title>CGRAN</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
</head>


<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li><a href="javascript:history.back()">CGRAN</a></li>
      <li><a target="_blank" href="http://gnuradio.org/">GNU Radio</a></li>
      <li><a target="_blank" href="http://libvolk.org/">VOLK</a></li>
      <li><a target="_blank" href="https://github.com/gnuradio/pybombs">PyBOMBS</a></li>
      <li><a href="{% url 'ootlist:submit' %}">Submit your OOT</a></li>
    </ul>
  </div>
</nav>


<div class="container" style="padding: 20px 20px 20px 20px;">
<h3>Submitting a GNU Radio Out of Tree (OOT) Module</h1>
<p>To have your OOT show up in CGRAN, you don't actually submit it directly.
CGRAN works by automatically parsing the gr-recipes and gr-etcetera PyBOMBS recipes.
Having your OOT in the form of a PyBOMBS recipe will make it real quick for people
to install and use it.  Use the following steps to add your OOT to gr-etcetera:
<ol>
  <li>Create MANIFEST.md in the root directory of your OOT <a href="https://raw.githubusercontent.com/osh/gr-eventstream/master/MANIFEST.md">(example manifest)</a></li>
  <li>Create the PyBOMBS Recipe File (.lwr file) <a href="https://wiki.gnuradio.org/index.php/OutOfTreeModulesConfig">instructions at the bottom of this page</a></li>
  <li>Add your .lwr file to <a href="https://github.com/gnuradio/gr-etcetera">gr-etcetera</a> in the form of a pull request, look at closed pull requests for examples</li>
  <li>Once your pull request is merged in, and CGRAN does its daily update, your OOT should show up</li>
  <li>If your OOT does not seem to show up, check that it is not included in the blacklist located <a href="https://github.com/gnuradio/cgran/blob/master/blacklist.txt">here</a></li>
</ol>

<a href="{% url 'ootlist:index' %}">back</a>

</div>
</body>

{% include 'ootlist/footer.html' %}

</html>